version: "3.9"

services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres_tickets
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}:postgres
      - POSTGRES_USER=${POSTGRES_USER}:postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}:postgres
      - POSTGRES_PORT=${POSTGRES_PORT}:5432
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    networks:
      - services

  app:
    build:
      context: ../
      dockerfile: src/app/Dockerfile
    container_name: app_tickets
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ../.env
#    depends_on:
#      - postgres
#      - rabbitmq
    networks:
      - services

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  services:
    name: tickets
